### ISSUE TITLE
Installation of DT0.8.2 might be corrupted?

### ISSUE THREAD

**Issue by drosales95** [silvxlabs/DripTorch#142] opened 2022-11-30 21:39 UTC
I'm doing a fresh installation of both Anaconda and my environment today and in the process of installing Driptorch I ran into this issue:

CondaVerificationError: The package for driptorch located at C:\Users\dgiron\.conda\pkgs\driptorch-0.8.2-py310_0
appears to be corrupted. The path 'Lib/0/site-packages/driptorch/warnings.py' specified in the package manifest cannot be found.

When looking at the folder structure I noticed that the site-packages were located directly underneath Lib and that adding another folder '0' helped with the installation, but it still doesn't recognize driptorch as being installed. Note that this only happens when installing driptorch through conda. I can get a working environment with driptorch working by using pip install.

To be clear I uninstalled Anaconda and think I deleted all the local files and cached information before reinstalling.

Let me know if there is any other information I can provide

**Comment by lucaswells** [comment] 2022-12-01 19:35
Hi @drosales95, I was unable to reproduce this error on macOS. Can you post the command you used to install driptorch?

**Comment by lucaswells** [comment] 2022-12-09 17:53
@drosales95, please reopen this issue if you continuous to experience installation issues. I'm closing this issue for now.

**Closed by lucaswells** 2022-12-09 17:53 UTC
